import assert from 'node:assert/strict';
import test from 'node:test';
import path from 'node:path';
import os from 'node:os';
import { mkdtemp, mkdir, writeFile, readFile, cp, symlink, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { PNG } from 'pngjs';
import { rootDir } from '../scripts/lib/project.mjs';
import { compileMetricFacts, metricIdentity } from '../scripts/lib/metric-source.mjs';
import { bytesDigest, fileManifest } from '../scripts/lib/workflow-files.mjs';
import { startAsset, continueAsset, reviewAsset, sealAsset, showAsset, buildContext } from '../scripts/lib/asset-workflow.mjs';
import { planAssetPublication, publishAssetPlan, releasePublished } from '../scripts/lib/workflow-publication.mjs';
import { refreshAssetWorkspace, processingSourceList, archiveProcessingSources } from '../scripts/lib/workflow-recovery.mjs';
import { renderAssetReview } from '../scripts/lib/workflow-review.mjs';
import { startStaticServer } from '../scripts/dev-server.mjs';
import { recordAssetBatch } from '../scripts/lib/workflow-batch.mjs';
import { recordWorkflowFeedback } from '../scripts/lib/workflow-feedback.mjs';
import { recordAssetVersion } from '../scripts/lib/workflow-assets.mjs';

const literal = '示例公司 A，2026 年第一季度收入 100 亿元，净利润 20 亿元。';
function facts(text = literal, id = 'example-a') {
  const part = (quote) => ({ quote, anchor: { type: 'text-range', range: [text.indexOf(quote), text.indexOf(quote) + quote.length] } });
  return { protocol: 'source-facts/v1', subject: { type: 'company', id, name: '示例公司 A' }, period: '2026 年第一季度', basis: 'unspecified',
    context: [{ field: 'subject', ...part('示例公司 A') }, { field: 'period', ...part('2026 年第一季度') }],
    metrics: [{ id: 'revenue', name: '收入', value: '100', unit: '亿元', currency: 'CNY', literal: '100 亿元', ...part('收入 100 亿元') }, { id: 'net-profit', name: '净利润', value: '20', unit: '亿元', currency: 'CNY', literal: '20 亿元', ...part('净利润 20 亿元') }] };
}
const textSource = { locator: 'input/processed/example.txt', format: 'text', charLength: literal.length, digest: bytesDigest(literal), availability: 'local-only' };
test('text and PNG facts normalize to identical metric identities and exact values', () => {
  const input = facts();
  const text = compileMetricFacts(input, { key: 'example', source: textSource, text: literal });
  const picture = structuredClone(input);
  for (const [i, item] of [...picture.context, ...picture.metrics].entries()) item.anchor = { type: 'image-box', box: [0, i * 10, 100, 10] };
  const image = compileMetricFacts(picture, { key: 'example', source: { locator: 'source.png', digest: bytesDigest('image'), width: 100, height: 100 } });
  assert.deepEqual(text.record.metrics.map((item) => [metricIdentity(text.record, item), item.value, item.unit, item.currency]), image.record.metrics.map((item) => [metricIdentity(image.record, item), item.value, item.unit, item.currency]));
  assert.equal(text.inventory.objects.length, 4);
});
test('omissions, wrong anchors, fabricated values and currency swaps fail before authoring', () => {
  const input = facts(); input.metrics.pop();
  assert.throws(() => compileMetricFacts(input, { key: 'example', source: textSource, text: literal }), /Unaccounted Source text/);
  const badValue = facts(); badValue.metrics[0].value = '101';
  assert.throws(() => compileMetricFacts(badValue, { key: 'example', source: textSource, text: literal }), /literal and value disagree/);
  const badAnchor = facts(); badAnchor.metrics[0].anchor.range[0]++;
  assert.throws(() => compileMetricFacts(badAnchor, { key: 'example', source: textSource, text: literal }), /exact text range/);
  const badCurrency = facts(); badCurrency.metrics[0].currency = 'USD';
  assert.throws(() => compileMetricFacts(badCurrency, { key: 'example', source: textSource, text: literal }), /currency disagrees/);
});
async function fixture(t) {
  const root = await mkdtemp(path.join(os.tmpdir(), 'trace-asset-workflow-test-'));
  for (const dir of ['scripts', 'docs']) await cp(path.join(rootDir, dir), path.join(root, dir), { recursive: true });
  for (const file of ['package.json', 'pnpm-lock.yaml', 'AGENTS.md', 'CONTEXT.md', '.gitignore']) await cp(path.join(rootDir, file), path.join(root, file));
  for (const dir of ['input/pending', 'data', 'src']) await mkdir(path.join(root, dir), { recursive: true });
  await symlink(path.join(rootDir, 'node_modules'), path.join(root, 'node_modules'));
  await writeFile(path.join(root, 'src/runtime.js'), '// fixture runtime\n');
  await writeFile(path.join(root, 'index.html'), '<html><script src="data/metric-observations.js"></script></html>');
  await writeFile(path.join(root, 'data/metric-observations.js'), '// Generated by update:metric-catalog. Do not edit.\nwindow.METRIC_OBSERVATIONS = [];\n');
  t.after(() => rm(root, { recursive: true, force: true }));
  return root;
}
async function intake(root, key = 'example-a-q1', input = facts()) {
  await writeFile(path.join(root, `input/pending/${key}.txt`), literal);
  return startAsset({ source: `input/pending/${key}.txt`, key, facts: input }, root);
}
function reviewFor(current, decision = 'accepted') {
  return { reviewToken: current.reviewToken, attestation: { reviewer: 'synthetic-test-reviewer', decision, note: 'Synthetic fixture; not a real dataset acceptance' }, attention: { status: 'closed', closureNote: 'Source and rows inspected in the fixture' }, manualCheckDecisions: [{ checkId: 'adapter:source-coverage-review', status: 'passed', evidenceDigests: [current.plan.sourceDigest, current.plan.sourceCoverageDigest], note: 'Fixture coverage compared' }] };
}
async function completed(root, key, input) {
  const started = await intake(root, key, input);
  const current = await continueAsset(started.buildId, root);
  await reviewAsset(started.buildId, reviewFor(current), root);
  await sealAsset(started.buildId, root);
  return started;
}
test('text intake to sealed Build preserves source, isolates drafts, requires review and emits a usable sheet', async (t) => {
  const root = await fixture(t);
  const base = await fileManifest(root);
  const started = await intake(root);
  const repeated = await startAsset({ source: 'input/pending/example-a-q1.txt', key: 'example-a-q1', facts: facts() }, root);
  assert.equal(repeated.buildId, started.buildId);
  let current = await continueAsset(started.buildId, root);
  assert.equal(current.next, 'review');
  assert.equal((await fileManifest(root)).digest, base.digest, 'canonical files stay unchanged during authoring');
  await assert.rejects(sealAsset(started.buildId, root), /BASELINE_STAGED/);
  await assert.rejects(reviewAsset(started.buildId, { ...reviewFor(current), reviewToken: bytesDigest('foreign') }, root), /exact processing-sheet token/);
  const sheet = await renderAssetReview(started.buildId, root);
  const html = await readFile(sheet.path, 'utf8');
  assert.ok(html.includes('100') && html.includes('downloadReview') && !html.includes('{{CONTENT}}'));
  const missingHuman = reviewFor(current); delete missingHuman.attestation;
  assert.equal((await reviewAsset(started.buildId, missingHuman, root)).state, 'AUTHORED');
  await reviewAsset(started.buildId, reviewFor(current), root);
  assert.equal((await sealAsset(started.buildId, root)).state, 'SEALED');
  // A shared catalog addition is not a change to this Build's contribution.
  await writeFile(path.join(started.workspace, 'data/dataset-manifest.js'), '// unrelated registration change\n');
  assert.equal((await showAsset(started.buildId, root)).fresh, true);
  await writeFile(path.join(started.workspace, 'src/new-runtime.js'), '// newly introduced executable dependency\n');
  assert.equal((await showAsset(started.buildId, root)).fresh, false);
});
test('publication rejects partial or changed candidates, commits atomically, recovers unknown outcomes and is idempotent', async (t) => {
  const root = await fixture(t);
  const started = await completed(root, 'example-a-q1');
  const plan = await planAssetPublication([started.buildId], root);
  await assert.rejects(publishAssetPlan(plan.planDigest, root, { beforePointerCommit: () => { throw new Error('simulated disk failure'); } }), /simulated disk/);
  assert.equal(existsSync(path.join(root, 'output/publications/current.json')), false);
  await assert.rejects(publishAssetPlan(plan.planDigest, root, { afterPointerCommit: () => { throw new Error('simulated unknown outcome'); } }), /unknown outcome/);
  const receipt = await publishAssetPlan(plan.planDigest, root);
  assert.equal(receipt.state, 'PUBLISHED');
  assert.deepEqual(await publishAssetPlan(plan.planDigest, root), receipt);
  assert.equal(existsSync(path.join(root, 'data/metric-observations/example-a-q1.json')), false);
  const server = await startStaticServer({ root, published: true }); t.after(server.close);
  const response = await fetch(server.url, { redirect: 'manual' });
  assert.equal(response.status, 302);
  const location = response.headers.get('location');
  assert.ok(location.includes(receipt.publishedDigest.slice(7)));
  const catalog = await (await fetch(new URL(location + 'data/metric-observations.js', server.url))).text();
  assert.match(catalog, /example-a-q1/);
  const failed = await releasePublished({ publishedDigest: receipt.publishedDigest, target: 'site' }, root, { runRelease: () => { throw new Error('build failed'); } });
  assert.equal(failed.state, 'RELEASE_FAILED');
  assert.equal(JSON.parse(await readFile(path.join(root, 'output/publications/current.json'))).publishedDigest, receipt.publishedDigest);
  const retried = await releasePublished({ publishedDigest: receipt.publishedDigest, target: 'site', retryOf: failed.attemptId }, root, { runRelease: async ({ candidate }) => { await mkdir(path.join(candidate, '_site')); await writeFile(path.join(candidate, '_site/index.html'), 'fixture'); } });
  assert.equal(retried.state, 'RELEASED'); assert.notEqual(retried.attemptId, failed.attemptId);
});
test('concurrent plans conflict without blind retry and duplicate observations cannot hide under another Source key', async (t) => {
  const root = await fixture(t);
  const a = await completed(root, 'first-source');
  // Different immutable source bytes for the second task; semantic identity
  // remains the same so the combined projection must detect duplication.
  await writeFile(path.join(root, 'input/pending/second-source.md'), literal + '\n');
  const b = await startAsset({ source: 'input/pending/second-source.md', key: 'second-source', facts: facts(literal + '\n') }, root);
  const next = await continueAsset(b.buildId, root); await reviewAsset(b.buildId, reviewFor(next), root); await sealAsset(b.buildId, root);
  await assert.rejects(planAssetPublication([a.buildId, b.buildId], root), /Metric already exists/);
  const planA = await planAssetPublication([a.buildId], root);
  const planB = await planAssetPublication([b.buildId], root);
  await publishAssetPlan(planA.planDigest, root);
  await assert.rejects(publishAssetPlan(planB.planDigest, root), (error) => error.code === 'PUBLICATION_CONFLICT');
  await assert.rejects(publishAssetPlan(planB.planDigest, root), (error) => error.code === 'PUBLICATION_CONFLICT');
});
test('source relocation consumes an exact operator-confirmed full list and never overwrites a different archive', async (t) => {
  const root = await fixture(t); const started = await intake(root);
  const list = await processingSourceList(root);
  await assert.rejects(archiveProcessingSources({ kind: 'review-completed', operator: 'fixture', confirmed: true, sourceListDigest: bytesDigest('old') }, root), /list changed/);
  await mkdir(path.join(root, 'input/processed')); await writeFile(path.join(root, 'input/processed/example-a-q1.txt'), 'different');
  await assert.rejects(archiveProcessingSources({ kind: 'review-completed', operator: 'fixture', confirmed: true, sourceListDigest: list.digest }, root), /Archive collision/);
  assert.ok(existsSync(path.join(root, 'input/processing/example-a-q1.txt')));
  await rm(path.join(root, 'input/processed/example-a-q1.txt'));
  const receipt = await archiveProcessingSources({ kind: 'review-completed', operator: 'fixture', confirmed: true, sourceListDigest: list.digest }, root);
  assert.equal(receipt.moved.length, 1); assert.ok(existsSync(path.join(started.workspace, 'input/processing/example-a-q1.txt')));
});

test('PNG Source follows the same complete data-only workflow and wrong image regions fail', async (t) => {
  const root = await fixture(t);
  const png = new PNG({ width: 100, height: 100 }); png.data.fill(255);
  await writeFile(path.join(root, 'input/pending/picture.png'), PNG.sync.write(png));
  const input = facts();
  for (const [i, item] of [...input.context, ...input.metrics].entries()) item.anchor = { type: 'image-box', box: [0, i * 10, 100, 10] };
  const started = await startAsset({ source: 'input/pending/picture.png', key: 'picture-source', facts: input }, root);
  const artifact = 'data/assets/raster-annotations/picture-source/logo.png';
  const recipe = 'input/icon-crop-specs/picture-source.json';
  const assetBytes = PNG.sync.write(png);
  await mkdir(path.dirname(path.join(started.workspace, artifact)), { recursive: true });
  await mkdir(path.dirname(path.join(started.workspace, recipe)), { recursive: true });
  await writeFile(path.join(started.workspace, artifact), assetBytes);
  await writeFile(path.join(started.workspace, recipe), JSON.stringify({ source: 'input/processed/picture-source.png', runtimeOutputDir: 'data/assets/raster-annotations/picture-source', crops: [{ key: 'logo', runtimeOutput: 'logo.png', rect: [0, 0, 100, 100] }] }));
  await recordAssetVersion({ subject: 'fixture logo', artifact, recipe, review: { reviewer: 'synthetic-reviewer', decision: 'accepted', note: 'Synthetic asset fixture', artifactDigest: bytesDigest(assetBytes) } }, started.workspace);
  const current = await continueAsset(started.buildId, root);
  assert.equal(current.metrics.length, 2);
  assert.equal(current.source.width, 100);
  await reviewAsset(started.buildId, reviewFor(current), root);
  assert.equal((await sealAsset(started.buildId, root)).state, 'SEALED');
  const plan = await planAssetPublication([started.buildId], root);
  const publication = await publishAssetPlan(plan.planDigest, root);
  const publishedRoot = path.join(root, 'output/publications/trees', publication.publishedDigest.slice(7));
  assert.ok(existsSync(path.join(publishedRoot, recipe)), 'crop recipe must travel with the accepted asset');
  assert.equal(JSON.parse(await readFile(path.join(publishedRoot, 'data/assets/catalog.json'))).entries[0].reusable, true);
  input.metrics[0].anchor.box = [99, 0, 20, 10];
  assert.throws(() => compileMetricFacts(input, { key: 'picture-source', source: { width: 100, height: 100 } }), /outside/);
});

test('new feedback invalidates a sealed isolated result and blocks review until resolved', async (t) => {
  const root = await fixture(t);
  const started = await completed(root, 'feedback-source');
  const current = await showAsset(started.buildId, root);
  await recordWorkflowFeedback(started.buildId, { feedbackId: 'FB-001', regionId: 'REG-001', ruleIds: ['G11'], cause: 'execution-gap', status: 'open', beforeEvidenceDigests: [current.plan.sourceDigest] }, await buildContext(started.buildId, root));
  assert.equal((await showAsset(started.buildId, root)).fresh, false);
  await assert.rejects(planAssetPublication([started.buildId], root), /not fresh/);
  const refreshed = await continueAsset(started.buildId, root);
  assert.notEqual(refreshed.reviewToken, current.reviewToken);
  const reviewed = await reviewAsset(started.buildId, reviewFor(refreshed), root);
  assert.equal(reviewed.state, 'AUTHORED');
  await assert.rejects(sealAsset(started.buildId, root), /BASELINE_STAGED/);
});
test('refresh after an unrelated publication preserves owned data and requires a new seal', async (t) => {
  const root = await fixture(t);
  const a = await completed(root, 'first-source');
  const text = literal + '\n';
  await writeFile(path.join(root, 'input/pending/other-source.md'), text);
  const b = await startAsset({ source: 'input/pending/other-source.md', key: 'other-source', facts: facts(text, 'other-subject') }, root);
  const next = await continueAsset(b.buildId, root); await reviewAsset(b.buildId, reviewFor(next), root); await sealAsset(b.buildId, root);
  const plan = await planAssetPublication([a.buildId], root); await publishAssetPlan(plan.planDigest, root);
  const refreshed = await refreshAssetWorkspace(b.buildId, root);
  assert.equal(refreshed.state, 'AUTHORED');
  await assert.rejects(planAssetPublication([b.buildId], root), /not fresh, sealed/);
  const current = await continueAsset(b.buildId, root); await reviewAsset(b.buildId, reviewFor(current), root); await sealAsset(b.buildId, root);
  const newPlan = await planAssetPublication([b.buildId], root);
  assert.equal((await publishAssetPlan(newPlan.planDigest, root)).state, 'PUBLISHED');
});

test('batch workers persist independent progress and one rejected source cannot accept its peers', async (t) => {
  const root = await fixture(t);
  await writeFile(path.join(root, 'input/pending/good.txt'), literal);
  await writeFile(path.join(root, 'input/pending/bad.md'), literal + '\n');
  const bad = facts(literal + '\n'); bad.metrics[0].value = '999';
  const batch = await recordAssetBatch({ sources: [
    { source: 'input/pending/good.txt', key: 'good', facts: facts() },
    { source: 'input/pending/bad.md', key: 'bad', facts: bad },
  ] }, { root, concurrency: 2 });
  assert.equal(batch.results.length, 2);
  assert.equal(batch.results.filter((item) => item.error).length, 1, JSON.stringify(batch.results));
  const good = batch.results.find((item) => item.result);
  assert.equal(good.result.state, 'AUTHORED'); assert.equal(good.result.next, 'review');
  const saved = JSON.parse(await readFile(batch.manifestPath, 'utf8'));
  assert.equal(saved.results.length, 2);
  assert.equal(existsSync(path.join(root, 'output/publications/current.json')), false);
});
