import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import { mkdtemp, mkdir, writeFile, readFile, rm, readdir, symlink } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { atomicJson, readJson, fileManifest, cloneFiles, freezeSnapshot } from '../scripts/lib/workflow-files.mjs';
import { compactWorkspace, materializeWorkspace, readInside } from '../scripts/lib/workspace-storage.mjs';
import { encodeRecord, decodeRecord } from '../scripts/lib/record-storage.mjs';
import { createPreviewManifest } from '../scripts/lib/workbench-manifest.mjs';
import { cleanupArtifacts } from '../scripts/lib/artifact-cleanup.mjs';

async function fixture(t) {
  const root = await mkdtemp(path.join(os.tmpdir(), 'trace-storage-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const put = async (folder, file, contents) => { await mkdir(path.dirname(path.join(folder, file)), { recursive: true }); await writeFile(path.join(folder, file), contents); };
  await put(root, 'index.html', 'index');
  await put(root, 'data/assets/icon-references/a/sheet.png', Buffer.alloc(100000, 123));
  await put(root, 'data/datasets/a.js', 'old adapter');
  await put(root, 'data/datasets/deleted.js', 'removed by author');
  const base = await freezeSnapshot({ root, ...await fileManifest(root), published: false }, root);
  const workspace = path.join(root, 'output/builds/build-a/workspace');
  await cloneFiles(base.root, workspace, base.entries.map((e) => e.path));
  await put(workspace, 'scripts/lib/record-storage.mjs', '// supported');
  await atomicJson(path.join(workspace, 'output/workflow/base.json'), base);
  return { root, workspace, base, put };
}
test('asset sharing then full compaction preserves exact logical manifest and author edits', async (t) => {
  const { root, workspace, base, put } = await fixture(t);
  await put(workspace, 'data/datasets/a.js', 'edited adapter');
  await rm(path.join(workspace, 'data/datasets/deleted.js'));
  const before = await fileManifest(workspace);
  const assets = await compactWorkspace(workspace, { assetsOnly: true });
  assert.equal(assets.logicalBytesSaved, 100000);
  assert.equal(existsSync(path.join(workspace, 'data/assets/icon-references/a/sheet.png')), false);
  assert.deepEqual(await fileManifest(workspace), before);
  await compactWorkspace(workspace);
  assert.equal(existsSync(path.join(workspace, 'index.html')), false);
  assert.equal(await readFile(readInside(workspace, 'index.html'), 'utf8'), 'index');
  assert.equal(await readFile(path.join(workspace, 'data/datasets/a.js'), 'utf8'), 'edited adapter');
  assert.deepEqual(await createPreviewManifest()(workspace), before);
  const projection = path.join(root, 'projected');
  await cloneFiles(workspace, projection, before.entries.map((e) => e.path));
  assert.deepEqual(await fileManifest(projection), before);
  await materializeWorkspace(workspace);
  await put(workspace, 'index.html', 'independent edit');
  assert.equal(await readFile(path.join(base.root, 'index.html'), 'utf8'), 'index');
  assert.equal(existsSync(path.join(workspace, 'data/datasets/deleted.js')), false);
});
test('modified shared bytes, missing bytes and redirected storage fail closed', async (t) => {
  const { workspace, base, put } = await fixture(t);
  await compactWorkspace(workspace);
  await put(base.root, 'index.html', 'tampered');
  await assert.rejects(materializeWorkspace(workspace), /changed/);
  await rm(path.join(base.root, 'index.html'));
  await assert.rejects(fileManifest(workspace), /ENOENT/);
  await put(base.root, 'index.html', 'index');
  await rm(path.join(base.root, 'index.html'));
  await symlink('/etc/hosts', path.join(base.root, 'index.html'));
  assert.throws(() => readInside(workspace, 'index.html'), /symlinks/);
});
test('shared record chunks preserve logical receipts and reuse unchanged directories', async (t) => {
  const { root, workspace } = await fixture(t);
  const file = path.join(root, 'output/builds/build-a/manifest.json');
  const artifacts = Array.from({ length: 160 }, (_, n) => ({ path: `data/assets/company-${Math.floor(n / 10)}/a-${n}`, digest: `sha256:${'1'.repeat(64)}`, role: 'asset' }));
  const value = { receipts: [{ digest: 'unchanged-receipt-digest', payload: { artifacts } }] };
  const encoded = await encodeRecord(file, value);
  assert.ok(encoded.receipts[0].payload.artifacts.$traceList);
  assert.deepEqual(await decodeRecord(file, encoded), value);
  await atomicJson(file, value);
  assert.deepEqual(await readJson(file), value);
  await mkdir(path.join(workspace, 'output'), { recursive: true });
  await symlink(path.join(root, 'output/builds'), path.join(workspace, 'output/builds'));
  assert.deepEqual(await readJson(path.join(workspace, 'output/builds/build-a/manifest.json')), value, 'frozen child scripts resolve the shared Build store through its link');
  const store = path.join(root, 'output/storage/lists'), count = (await readdir(store)).length;
  const next = structuredClone(value); next.receipts[0].payload.artifacts[0].digest = `sha256:${'2'.repeat(64)}`;
  await encodeRecord(file, next);
  assert.equal((await readdir(store)).length, count + 1);
  const chunk = encoded.receipts[0].payload.artifacts.chunks[0];
  await writeFile(path.join(store, `${chunk}.json`), '[]');
  await assert.rejects(decodeRecord(file, encoded), /changed/);
  await rm(path.join(workspace, 'scripts/lib/record-storage.mjs'));
  assert.deepEqual(await encodeRecord(file, value), value, 'frozen old tools keep plain JSON');
});

test('compaction can be repeated, local overrides survive and shared index corruption is rejected', async (t) => {
  const { workspace, base, put } = await fixture(t);
  await compactWorkspace(workspace);
  assert.equal((await compactWorkspace(workspace)).removedFiles, 0);
  const compacted = await fileManifest(workspace);
  await compactWorkspace(workspace, { assetsOnly: true });
  assert.deepEqual(await fileManifest(workspace), compacted, 'sharing assets again retains the full inherited view');
  await put(workspace, 'index.html', 'local override');
  await compactWorkspace(workspace);
  assert.equal(await readFile(readInside(workspace, 'index.html'), 'utf8'), 'local override');
  await materializeWorkspace(workspace);
  assert.equal(await readFile(path.join(workspace, 'index.html'), 'utf8'), 'local override');
  await compactWorkspace(workspace);
  await writeFile(path.join(base.root, '.trace-snapshot.json'), '[]');
  assert.throws(() => readInside(workspace, 'data/datasets/a.js'), /manifest changed/);
});
test('capacity reporting works with a running service and locks; deletion remains fenced', async (t) => {
  const { root, put } = await fixture(t);
  await put(root, 'output/builds/build-a/manifest.json', JSON.stringify({ buildId: 'build-a', state: 'AUTHORED' }));
  await atomicJson(path.join(root, 'output/workbench/servers/test.json'), { pid: process.pid });
  await put(root, 'output/builds/build-a/.workflow-operation.lock', '{}');
  const result = await cleanupArtifacts(root);
  assert.equal(result.blockers.length, 2);
  assert.ok(result.groups['output/builds'].logicalBytes > 0);
  await assert.rejects(cleanupArtifacts(root, { completed: true }), /Finish\/recover/);
});
