import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { existsSync } from 'node:fs';
import { metricIdentity, validateMetricRecord, compileMetricFacts, SOURCE_FACTS_PROTOCOL } from './metric-source.mjs';
import { sourceDigest, resolveSourcePath } from './source-lifecycle.mjs';

export async function readMetricRecords(root) {
  const directory = path.join(root, 'data/metric-observations');
  if (!existsSync(directory)) return [];
  return Promise.all((await readdir(directory)).filter((name) => name.endsWith('.json')).sort().map(async (name) => {
    const record = JSON.parse(await readFile(path.join(directory, name), 'utf8'));
    if (name !== `${record.key}.json`) throw new Error(`Metric key/path mismatch: ${name}`);
    return record;
  }));
}
export function projectMetricCatalog(records) {
  const keys = new Set();
  const identities = new Map();
  for (const record of records) {
    validateMetricRecord(record);
    if (keys.has(record.key)) throw new Error(`Duplicate Source key: ${record.key}`);
    keys.add(record.key);
    for (const metric of record.metrics) {
      const identity = metricIdentity(record, metric);
      if (identities.has(identity)) throw new Error(`Metric already exists: ${identity} in ${identities.get(identity)} and ${record.key}; resolve provenance/conflict explicitly`);
      identities.set(identity, record.key);
    }
  }
  // Original media can be private. The viewer retains Source digests, quotes
  // and locators but never embeds raw reference bytes into a public bundle.
  return `// Generated by update:metric-catalog. Do not edit.\nwindow.METRIC_OBSERVATIONS = ${JSON.stringify(records, null, 2).replace(/</g, '\\u003c')};\n`;
}
export async function updateMetricCatalog(root, { check = false } = {}) {
  const records = await readMetricRecords(root);
  const expected = projectMetricCatalog(records);
  const file = path.join(root, 'data/metric-observations.js');
  if (check) {
    if (!existsSync(file) || await readFile(file, 'utf8') !== expected) throw new Error('Metric catalog is stale: run pnpm update:metric-catalog');
  } else {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, expected);
  }
  return records;
}
export async function verifyMetricRecords(root, key = null) {
  const all = await updateMetricCatalog(root, { check: true });
  const records = key ? all.filter((item) => item.key === key) : all;
  if (key && !records.length) throw new Error(`Metric Source not registered: ${key}`);
  for (const record of records) {
    const sourcePath = resolveSourcePath(record.source.locator, { projectRoot: root });
    if (existsSync(sourcePath)) {
      if (await sourceDigest(sourcePath) !== record.source.digest) throw new Error(`Source changed: ${record.key}`);
      if (record.source.format === 'text') {
        const text = new TextDecoder('utf-8', { fatal: true }).decode(await readFile(sourcePath));
        compileMetricFacts({ ...record, protocol: SOURCE_FACTS_PROTOCOL }, { key: record.key, source: record.source, text });
      }
    } else if (record.source.availability === 'public') {
      throw new Error(`Public Source missing: ${record.key}`);
    }
  }
  return { records: records.length, metrics: records.reduce((n, record) => n + record.metrics.length, 0) };
}
